---
title: "Three INCREDIBLY IMPORTANT notes about the schedule"
date: "2026-06-07T17:08"
categories: [course details]
---

::: {.callout-warning title="SUPER IMPORTANT"}
MAKE SURE YOU READ THIS—THIS IS VERY IMPORTANT!!!1!11!
:::

### 1: Course pace

This is a summer class, which means it moves a lot faster than a normal semester while keeping all the same content! In a normal summer class, you'd cover 14–15 sessions of content in just 7 weeks—that's essentially 2 weeks of content each week.

If you check the schedule page at the class website (make sure you scroll down!), you'll see that each week has 2 sessions. That means you'll have 2 sets of lectures, 2 lessons, and 2 exercises. Make sure you keep that in mind when planning out your schedule!

### 2: Choose-your-own-adventure week

The only exception is during July 13–17, where you'll notice that there are four sessions scheduled. THIS IS DIFFERENT. You will ***NOT*** complete 4 sessions in one week—that would be bonkers. Instead, it's a choose-your-own adventure week. Select *just one (1)* of the topics and do that. If you want extra credit, you can do others too. But **the expectation is just one**.

### 3: Final project deadline and end of class

Notice that the final project is due on July 26. That's *before* GSU's official finals week. That basically means that the class ends a week earlier than normal (this is also why I created a choose-your-own-adventure week).

That's on purpose.

The reason things need to end a little bit earlier is because you are all the last students I will ever teach at GSU! In the fall, I'm starting a new job as an assistant professor of international politics and policy at [Georgetown University in Qatar](https://guq.qatar.georgetown.edu/). My final day at GSU is July 31, and my family and I will be flying from Atlanta to Doha at the beginning of August.

This is a big exciting move—I've been hoping/trying to get back to the Middle East since I left in 2010 and I'm finally headed back! My research on international nonprofits, civil society, and global politics & policy is all continuing, and I'll still be teaching social science-y data science classes—just from Doha now.

However, I'm going to miss GSU! I have loved being here at the Andrew Young School and I've had a blast working with all you incredible students!

So, yeah, this is my last class here, and it has to be finished a little earlier to account for travel time. To accommodate that, I cut out one of the assignments I usually have, collapsed four sessions into a choose-just-one week, and moved up the final project deadline a week.
